import {invokeDomContent} from "./indexDomContent";
import { invokeSideBarButton } from "../sideBar/sideBarButtonContent";
import { loadNotePage } from "../notePage/notePage";
import { invokeTopBarButton } from "./TopBar/topBarButton";
import { addNote } from "../saveNote/userInputFunction";
import "./index.css";
invokeDomContent();
invokeSideBarButton();
invokeTopBarButton();
const button = document.getElementById('saveButton');
button.addEventListener('click', addNote);
const noteButton = document.getElementById('newNote');
noteButton.addEventListener('click',loadNotePage);