import {invokeDomContent} from "./indexDomContent";
import { invokeSideBarButton } from "../sideBar/sideBarButtonContent";
import { loadNotePage } from "../notePage/notePage";
import { invokeTopBarButton } from "./TopBar/topBarButton";
import { contentPage } from "./homePageContent/attributesHomePage";
import { invokeImages } from "../images/invokeImages/invokeImages";
import { loadUpComingPage } from "./upcomingPage/upcomingPage";
import "./index.css";
invokeDomContent();
invokeSideBarButton();
invokeTopBarButton();
contentPage();
invokeImages();
const noteButton = document.getElementById('newNote');
noteButton.addEventListener('click',loadNotePage);
const upcomingButton = document.getElementById ('upcoming');
upcomingButton.addEventListener('click', loadUpComingPage);
